title: Resume of Logan Morrison
description: [Hello! If you are reading this then you are likely considering me for a position. I hope you like what you see and hope to get to know you in an interview!]
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
